### ISSUE TITLE
Moulinette check fails (42Paris)

### ISSUE THREAD

**Issue by SERAC-SGM** [pasqualerossi/42-School-Exam-Rank-06#6]
Didn't pass test 08 (very long string sent in multiple times + a client disconnects in between)

Also need to remove the last bzero otherwise partial commands are cleared before being sent.

**Comment by pasqualerossi** [comment]
create a pull request with your code and I'll update it.

**Comment by SERAC-SGM** [comment]
Will do once I pass the exam
